include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
  exclude:
    - build/**
    - android/**
    - web/**

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_print: true
    use_key_in_widget_constructors: true
    unawaited_futures: error
